import React,{useState,useEffect,useCallback} from 'react'
import {LineChart,Line,XAxis,YAxis,Tooltip,Legend,ResponsiveContainer,BarChart,Bar,CartesianGrid,Cell} from 'recharts'
const COL={NORMAL:'#22c55e','EARLY DRIFT':'#3b82f6','PRE-FAULT':'#f59e0b',CRITICAL:'#ef4444'}
const P={rpm:['RPM','rpm'],speed:['Speed','km/h'],temperature:['Engine Temp','°C'],battery_voltage:['Battery','V'],fuel_consumption:['Fuel','L/h']}
const api=async(p,body)=>{try{const r=await fetch('/api'+p,body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}catch(e){throw new Error(e.message==='Failed to fetch'?'Backend unavailable. Start it with: python backend/app.py':e.message)}}
const Badge=({s})=><span className="badge" style={{background:COL[s]||'#64748b'}}>{s||'—'}</span>
const Gauge=({v=0})=>{const c=v>=85?'#22c55e':v>=70?'#3b82f6':v>=50?'#f59e0b':'#ef4444',R=52,L=2*Math.PI*R
return <svg width="140" height="140" viewBox="0 0 140 140"><circle cx="70" cy="70" r={R} stroke="#243047" strokeWidth="12" fill="none"/><circle cx="70" cy="70" r={R} stroke={c} strokeWidth="12" fill="none" strokeLinecap="round" strokeDasharray={L} strokeDashoffset={L*(1-v/100)} transform="rotate(-90 70 70)"/><text x="70" y="76" textAnchor="middle" fill="#e6ecf5" fontSize="30" fontWeight="700">{Math.round(v)}</text></svg>}
const Chart=({data,k,title,ex=true})=><div className="card"><h3>{title}</h3><ResponsiveContainer width="100%" height={210}><LineChart data={data}><CartesianGrid stroke="#243047"/><XAxis dataKey="t" hide/><YAxis domain={['auto','auto']} stroke="#8b9ab3" width={45}/><Tooltip contentStyle={{background:'#141b28',border:'1px solid #243047'}}/><Legend/><Line dataKey={k} name="Actual" stroke="#38bdf8" dot={false} isAnimationActive={false}/>{ex&&<Line dataKey={k+'_e'} name="Digital Twin Expected" stroke="#22c55e" strokeDasharray="5 4" dot={false} isAnimationActive={false}/>}</LineChart></ResponsiveContainer></div>
const Table=({a})=><table><thead><tr><th>Parameter</th><th>Actual</th><th>Expected</th><th>Deviation</th><th>Dev %</th><th>Score</th></tr></thead><tbody>{Object.entries(a.params).map(([k,v])=><tr key={k}><td>{P[k][0]}</td><td>{v.actual}</td><td>{v.expected}</td><td style={{color:Math.abs(v.z)>=1.2?'#f59e0b':'inherit'}}>{v.deviation>0?'+':''}{v.deviation}</td><td>{v.pct}%</td><td>{v.score}</td></tr>)}</tbody></table>
const Explain=({a})=>{const d=['temperature','rpm','battery_voltage','fuel_consumption'].map(k=>({n:P[k][0],v:a.params[k].contribution,l:a.params[k].level}));const lc={HIGH:'#ef4444',MEDIUM:'#f59e0b',LOW:'#22c55e'}
return <div className="card"><h3>Explainability — parameter contribution</h3><ResponsiveContainer width="100%" height={200}><BarChart data={d} layout="vertical"><XAxis type="number" domain={[0,100]} stroke="#8b9ab3"/><YAxis type="category" dataKey="n" stroke="#8b9ab3" width={90}/><Tooltip/><Bar dataKey="v" name="Contribution %">{d.map((x,i)=><Cell key={i} fill={lc[x.l]}/>)}</Bar></BarChart></ResponsiveContainer>
<p><b>Primary contributor:</b> {P[a.primary][0]} behaviour</p><p className="mut">{a.explanation}</p><p><b>Recommendation:</b> {a.recommendation}</p><p className="mut">Confidence {Math.round(a.confidence*100)}% · Drift score {a.drift} · Trend slope {a.slope}. Decision-support only; not a guaranteed diagnosis.</p></div>}
const Login=({on})=>{const[u,su]=useState('admin'),[p,sp]=useState('raider123'),[e,se]=useState('')
return <div className="login card"><h1>RAIDER AI</h1><p className="mut">Digital Twin Motorcycle Health Intelligence</p><label>Username</label><input value={u} onChange={x=>su(x.target.value)}/><label>Password</label><input type="password" value={p} onChange={x=>sp(x.target.value)}/><p style={{color:'#f87171'}}>{e}</p><button className="b" onClick={()=>u==='admin'&&p==='raider123'?on():se('Invalid credentials (demo: admin / raider123)')}>SIGN IN</button><p className="mut">Demo: admin / raider123</p></div>}

function Dashboard({d}){const a=d.analysis;if(!a)return <p>Loading…</p>
return <><div className="grid"><div className="card" style={{textAlign:'center'}}><h3>Overall Health</h3><Gauge v={a.health}/><div><Badge s={a.status}/> <span className="mut">{a.label}</span></div></div>
{Object.keys(P).map(k=><div className="card" key={k}><h3>{P[k][0]}</h3><div className="big">{a.params[k].actual}<span className="mut"> {P[k][1]}</span></div><div className="mut">Expected {a.params[k].expected} · dev {a.params[k].deviation}</div></div>)}</div>
<div className="grid g2" style={{marginTop:14}}><Chart data={d.series} k="temperature" title="Temperature: Actual vs Expected"/><Chart data={d.series} k="rpm" title="RPM: Actual vs Expected"/><Chart data={d.series} k="battery_voltage" title="Battery Voltage"/><Chart data={d.series} k="fuel_consumption" title="Fuel Consumption"/><Chart data={d.series} k="speed" title="Speed" ex={false}/><Chart data={d.series} k="drift" title="Behaviour Drift Score" ex={false}/></div>
<div style={{marginTop:14}}><Explain a={a}/></div></>}
function Live({d,run,setRun,reset}){const a=d.analysis
return <><div className="top"><h2>Live Monitoring</h2><div><button className="b" onClick={()=>setRun(true)}>START MONITORING</button><button className="b s" onClick={()=>setRun(false)}>PAUSE</button><button className="b r" onClick={reset}>RESET</button></div></div>
{a&&<div className="card"><Badge s={a.status}/> Mode: {d.mode} <Table a={a}/></div>}<div className="grid g2" style={{marginTop:14}}>{['temperature','rpm','battery_voltage','fuel_consumption'].map(k=><Chart key={k} data={d.series} k={k} title={P[k][0]}/>)}</div></>}
function Manual(){const[f,sf]=useState({rpm:3000,speed:45,temperature:72,battery_voltage:13.4,fuel_consumption:2.1}),[r,sr]=useState(null),[e,se]=useState('')
const go=async()=>{se('');try{sr((await api('/manual-analysis',f)).analysis)}catch(x){se(x.message);sr(null)}}
return <><h2>Manual Analysis</h2><div className="grid g2" style={{marginTop:14}}><div className="card"><h3>Enter values</h3>{Object.keys(P).map(k=><div key={k}><label>{P[k][0]} ({P[k][1]})</label><input value={f[k]} onChange={x=>sf({...f,[k]:x.target.value})}/></div>)}<br/><button className="b" onClick={go}>ANALYZE</button>{e&&<div className="err">{e}</div>}</div>
{r&&<div className="card" style={{textAlign:'center'}}><h3>Result</h3><Gauge v={r.health}/><div><Badge s={r.status}/> {r.label}</div><p className="mut">Drift score {r.drift}</p></div>}</div>
{r&&<><div className="card" style={{marginTop:14}}><Table a={r}/></div><div style={{marginTop:14}}><Explain a={r}/></div></>}</>}
function Twin({d}){const a=d.analysis;if(!a)return null
return <><h2>Digital Twin</h2><p className="mut">Expected healthy state predicted by a RandomForest model trained on healthy data (LSTM-ready). Speed is the operating context.</p><div className="grid g2" style={{marginTop:14}}>
<div className="card"><h3>Real motorcycle state</h3>{Object.keys(P).map(k=><div key={k} className="big" style={{fontSize:20}}>{P[k][0]}: {a.params[k].actual} {P[k][1]}</div>)}</div>
<div className="card" style={{borderColor:'#22c55e'}}><h3>Digital Twin expected state</h3>{Object.keys(P).map(k=><div key={k} className="big" style={{fontSize:20}}>{P[k][0]}: {a.params[k].expected} {P[k][1]} <span className="mut">({a.params[k].deviation>0?'+':''}{a.params[k].deviation})</span></div>)}</div></div>
<div className="card" style={{marginTop:14}}><Table a={a}/></div><div className="grid g2" style={{marginTop:14}}><Chart data={d.series} k="temperature" title="Temperature"/><Chart data={d.series} k="rpm" title="RPM"/></div></>}
function WhatIf(){const[f,sf]=useState({rpm:3000,speed:45,temperature:75,battery_voltage:13.6,fuel_consumption:1.8,duration:20}),[r,sr]=useState(null),[e,se]=useState('')
const go=async()=>{se('');try{sr(await api('/what-if',f))}catch(x){se(x.message);sr(null)}}
return <><h2>What-If Simulation</h2><div className="card" style={{marginTop:14}}><div className="grid">{Object.keys(f).map(k=><div key={k}><label>{P[k]?P[k][0]:'Duration (min)'}</label><input value={f[k]} onChange={x=>sf({...f,[k]:x.target.value})}/></div>)}</div><br/><button className="b" onClick={go}>RUN SIMULATION</button>{e&&<div className="err">{e}</div>}</div>
{r&&<div className="card" style={{marginTop:14}}><h3>Predicted temperature trend (expected now: {r.expected_temperature}°C) — risk: {r.risk_level}</h3><ResponsiveContainer width="100%" height={280}><LineChart data={r.points}><CartesianGrid stroke="#243047"/><XAxis dataKey="minute" stroke="#8b9ab3" unit="m"/><YAxis domain={['auto','auto']} stroke="#8b9ab3"/><Tooltip contentStyle={{background:'#141b28'}}/><Legend/><Line dataKey="healthy" name="Predicted healthy trend" stroke="#22c55e"/><Line dataKey="risk" name="Predicted risk trend" stroke="#ef4444"/></LineChart></ResponsiveContainer>
<table><thead><tr><th>Minutes</th>{r.points.filter(p=>p.minute%5===0&&p.minute).map(p=><th key={p.minute}>+{p.minute}</th>)}</tr></thead><tbody><tr><td>Risk °C</td>{r.points.filter(p=>p.minute%5===0&&p.minute).map(p=><td key={p.minute}>{p.risk}</td>)}</tr></tbody></table><p className="mut">{r.note}</p></div>}</>}
function Recovery({d}){const[r,sr]=useState(null),[e,se]=useState('');const a=d.analysis
const go=async()=>{se('');try{sr(await api('/recovery',{}))}catch(x){se(x.message)}}
const rc={'RECOVERY VERIFIED':'#22c55e','PARTIAL RECOVERY':'#f59e0b','NOT RECOVERED':'#ef4444'}
return <><h2>Safe Response & Recovery</h2><div className="card" style={{marginTop:14}}>{a&&<><Badge s={a.status}/> Health {a.health}<p><b>Safe Response:</b> {a.recommendation}</p></>}<p className="mut">Simulation only — the system never controls a real motorcycle.</p><button className="b" onClick={go}>SIMULATE RECOVERY</button>{e&&<div className="err">{e}</div>}</div>
{r&&<div className="card" style={{marginTop:14}}><h2 style={{color:rc[r.result]}}>{r.result}</h2><table><tbody><tr><td>Before</td><td>{r.before.temperature}°C</td><td>Health {r.before.health}</td><td><Badge s={r.before.status}/></td></tr><tr><td>Digital Twin expected</td><td>{r.expected_temperature}°C</td><td></td><td></td></tr><tr><td>After</td><td>{r.after.temperature}°C</td><td>Health {r.after.health}</td><td><Badge s={r.after.status}/></td></tr></tbody></table>
<p>Temperature path: {r.steps.map(s=>s.temperature+'°C').join(' → ')}</p><p>{r.advice}</p></div>}</>}
function History(){const[days,sd]=useState(1),[r,sr]=useState(null),[e,se]=useState('');const[cs,scs]=useState(''),[ce,sce]=useState('')
const q=cs?`start=${cs}&end=${ce}`:`days=${days}`
const load=useCallback(async()=>{try{sr(await api('/history?'+q));se('')}catch(x){se(x.message)}},[q]);useEffect(()=>{load()},[load])
return <><div className="top"><h2>History</h2><div>{[[1,'Today'],[7,'Last 7 days'],[30,'Last 30 days']].map(([n,l])=><button key={n} className={'b '+(!cs&&days===n?'':'s')} onClick={()=>{scs('');sd(n)}}>{l}</button>)}<a href={'/api/history?format=csv&'+q}><button className="b s">EXPORT CSV</button></a></div></div>
<div className="card"><label>Custom range (ISO, e.g. 2026-09-29T10:00:00)</label><div className="grid"><input value={cs} onChange={x=>scs(x.target.value)} placeholder="start"/><input value={ce} onChange={x=>sce(x.target.value)} placeholder="end"/></div></div>{e&&<div className="err">{e}</div>}
{r&&<><div className="grid g2" style={{marginTop:14}}>{[['health','Health score'],['temperature','Temperature'],['rpm','RPM'],['battery_voltage','Battery'],['drift','Drift']].map(([k,t])=><Chart key={k} data={r.records.map((x,i)=>({...x,t:i}))} k={k} title={t} ex={false}/>)}</div>
<div className="grid g2" style={{marginTop:14}}><div className="card"><h3>Anomaly events</h3><table><tbody>{r.anomalies.map(x=><tr key={x.id}><td>{x.ts.slice(11)}</td><td><Badge s={x.status}/></td><td className="mut">{x.message}</td></tr>)}</tbody></table></div>
<div className="card"><h3>Recovery events</h3><table><tbody>{r.recoveries.map(x=><tr key={x.id}><td>{x.ts.slice(11)}</td><td>{x.before_health}→{x.after_health}</td><td>{x.result}</td></tr>)}</tbody></table></div></div></>}</>}
function SimCtl({d,reset}){const[m,sm]=useState('');const go=async b=>{try{const r=await api('/simulate',b);sm('Applied: '+r.mode)}catch(x){sm(x.message)}}
return <><h2>Simulation Control</h2><p className="mut">Current mode: {d.mode} {d.analysis&&<Badge s={d.analysis.status}/>}</p><div className="card" style={{marginTop:14}}><h3>Condition</h3>{[['NORMAL MODE','NORMAL'],['EARLY DRIFT MODE','EARLY'],['PRE-FAULT MODE','PRE'],['CRITICAL MODE','CRITICAL']].map(([l,v])=><button className="b" key={v} onClick={()=>go({mode:v})}>{l}</button>)}<button className="b r" onClick={reset}>RESET TO HEALTHY</button></div>
<div className="card" style={{marginTop:14}}><h3>Inject drift</h3>{[['TEMPERATURE','temperature'],['RPM','rpm'],['BATTERY','battery_voltage'],['FUEL CONSUMPTION','fuel_consumption']].map(([l,v])=><button className="b s" key={v} onClick={()=>go({inject:v})}>INJECT {l} DRIFT</button>)}</div><p>{m}</p></>}
const NAV=[['dash','Dashboard'],['live','Live Monitoring'],['manual','Manual Analysis'],['twin','Digital Twin'],['expl','Drift & Explainability'],['whatif','What-If Simulation'],['rec','Safe Response / Recovery'],['hist','History'],['sim','Simulation Control']]
export default function App(){const[auth,sa]=useState(false),[pg,sp]=useState('dash'),[d,sd]=useState({series:[]}),[run,setRun]=useState(true),[err,se]=useState('')
const tick=useCallback(async()=>{try{sd(await api('/current'));se('')}catch(x){se(x.message)}},[])
useEffect(()=>{if(!auth||!run)return;tick();const i=setInterval(tick,1000);return()=>clearInterval(i)},[auth,run,tick])
const reset=async()=>{try{await api('/reset',{});sd({series:[]});await tick()}catch(x){se(x.message)}}
if(!auth)return <Login on={()=>sa(true)}/>
return <div className="app"><nav className="side"><h1>RAIDER AI</h1><small>Digital Twin Motorcycle Health Intelligence</small>{NAV.map(([k,l])=><button key={k} className={pg===k?'on':''} onClick={()=>sp(k)}>{l}</button>)}<button onClick={()=>sa(false)}>Logout</button></nav>
<main className="main">{err&&<div className="err">{err}</div>}{pg==='dash'&&<><div className="top"><h2>Dashboard</h2><span className="mut">{run?'● Live':'❚❚ Paused'}</span></div><Dashboard d={d}/></>}{pg==='live'&&<Live d={d} run={run} setRun={setRun} reset={reset}/>}{pg==='manual'&&<Manual/>}{pg==='twin'&&<Twin d={d}/>}
{pg==='expl'&&d.analysis&&<><h2>Behaviour Drift & Explainability</h2><div className="card" style={{margin:'14px 0'}}><Badge s={d.analysis.status}/> Drift score {d.analysis.drift}</div><div className="grid g2"><Chart data={d.series} k="drift" title="Behaviour drift score" ex={false}/><Explain a={d.analysis}/></div></>}
{pg==='whatif'&&<WhatIf/>}{pg==='rec'&&<Recovery d={d}/>}{pg==='hist'&&<History/>}{pg==='sim'&&<SimCtl d={d} reset={reset}/>}</main></div>}
